WebProgProje/Controllers/ArticleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProgProje.Data;
using WebProgProje.Models;

namespace WebProgProje.Controllers
{
    public class ArticleController : Controller
    {
        private readonly PaperContext paperContext;
        private readonly ApplicationDbContext AppContext;

        public ArticleController(PaperContext context, ApplicationDbContext context_2)
        {
            paperContext = context;
            AppContext = context_2;
        }

        public IActionResult Index()
        {
            List<Article> articles = paperContext.Articles.ToList();

            return View(articles);
        }

        
        public IActionResult Detail(int ?id)
        {
            if(id == null)
            {
                return NotFound();
            }

            Article article = paperContext.Articles.Find(id);

            if(article == null)
            {
                return NotFound();
            }
            else
            {
                List<Article> articles = paperContext.Articles.Include(x => x.Comments).ToList();
                var comments = (from comment in paperContext.Comments
                               where comment.ArticleId == article.ArticleId
                               select comment).ToList();

                List < Comment > commentsAsViewData = new List<Comment>();
                if(comments != null)
                {
                    foreach(var comment in comments)
                    {
                        commentsAsViewData.Add(comment);
                    }
                    ViewData["comments"] = commentsAsViewData;
                }
            }

            return View(article);
        }

        [HttpPost]
        public IActionResult Comment(string Comment, int id)
        {
            Comment comment = new Comment();
            comment.ArticleId = id;
            comment.Content = Comment;
            comment.DateOfCommenting = DateTime.Now;
            string user_name = AppContext.Users.Where(user => user.Email == User.Identity.Name).Select(user => user.UserFirstName).FirstOrDefault();
            comment.UserName = user_name + "  (" + User.Identity.Name + ")";
            paperContext.Comments.Add(comment);
            paperContext.SaveChanges();

            List<Article> articles = paperContext.Articles.ToList();

            var the_article = from article in articles
                              where article.ArticleId == id
                              select article;
            foreach(var article in the_article)
            {
                article.Comments.Add(comment);
                paperContext.SaveChanges();
            }
            return RedirectToAction("");
        }
    }
}

WebProgProje/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebProgProje.Models;

namespace WebProgProje.Controllers
{
    public class ContactController : Controller
    {
        PaperContext paperContext;

        public ContactController(PaperContext context)
        {
            paperContext = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult AddContact([Bind("Name, Email, Phone, Content")] Contact contact)
        {
            Contact _contact = new Contact();

            _contact.Name = contact.Name;
            _contact.Email = contact.Email;
            _contact.Phone = contact.Phone;
            _contact.Content = contact.Content;
            _contact.DateOfComment = DateTime.Now;
            _contact.isRead = false;

            paperContext.Contacts.Add(_contact);
            paperContext.SaveChanges();

            return View();
        }


    }
}

WebProgProje/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<UserInfo> SignInManager
@inject UserManager<UserInfo> UserManager


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Sergey Pozhilov (GetTemplate.com)">

    <title>Yusuf Sönmez</title>

    <link rel="shortcut icon" href="/images/gt_favicon.png">

    <link rel="stylesheet" media="screen" href="http://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/css/font-awesome.min.css" rel="stylesheet" />

    <!-- Custom styles for our template -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet" media="screen" />
    <link rel="stylesheet" href="/css/main.css">

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="assets/js/html5shiv.js"></script>
    <script src="assets/js/respond.min.js"></script>
    <![endif]-->
    <style>
        a {
            text-decoration: none;
        }
    </style>
</head>

<body class="home">
    <!-- Fixed navbar -->
    <div class="navbar navbar-inverse navbar-fixed-top headroom">
        <div class="container">
            <div class="navbar-header">
                <!-- Button for smallest screens -->
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
                <a class="navbar-brand" asp-controller="Home" asp-action="Index"><img width="158" height="40" src="/images/YusufSönmezAsılLogo.png" alt="Yusuf Sönmez"></a>
            </div>
            <div class="navbar-collapse collapse">

                <ul class="nav navbar-nav pull-right">
                    <li class="active"><a asp-controller="Home" asp-action="Index">Ana Sayfa</a></li>

                    <li><a asp-controller="Article" asp-action="Index">Yazılar</a></li>

                    <li><a asp-controller="Contact" asp-action="Index">İletişim</a></li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admin"))
                        {

                            <li><a asp-controller="Admin" asp-action="Index">Admin</a></li>
                        }
                        else if (User.IsInRole("User"))
                        {

                        }
                    }

                    <partial name="_LoginPartial" />
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
    <!-- /.navbar -->

    <header id="head" class="secondary"></header>

    @RenderBody()

    <!-- Social links. TODO: replace by link/instructions in template -->
    <section id="social">
        <div class="container">
            <div class="wrapper clearfix">
                <!-- AddThis Button BEGIN -->
                <div class="addthis_toolbox addthis_default_style">
                    <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
                    <a class="addthis_button_tweet"></a>
                    <a class="addthis_button_linkedin_counter"></a>
                    <a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
                </div>
                <!-- AddThis Button END -->
            </div>
        </div>
    </section>
    <!-- /social links -->


    <footer id="footer" class="top-space">

        <div class="footer1">
            <div class="container">
                <div class="row">

                    <div class="col-md-3 widget">
                        <h3 class="widget-title">İletişim</h3>
                        <div class="widget-body">
                            <p>
                                +90 (554) 660 37 82<br>
                                <a href="mailto:#">yusufsn54@gmail.com</a><br>
                                <br>
                                Adapazarı, Sakarya, Türkiye
                            </p>
                        </div>
                    </div>

                    <div class="col-md-3 widget">
                        <h3 class="widget-title">Beni Takip Et</h3>
                        <div class="widget-body">
                            <p class="follow-me-icons">
                                <a href="https://twitter.com/home"><i class="fa fa-twitter "></i></a>
                                <a href=""><i class="fa fa-dribbble fa-2"></i></a>
                                <a href="https://github.com/YusufSonmezz"><i class="fa fa-github "></i></a>
                                <a href=""><i class="fa fa-facebook fa-2"></i></a>
                            </p>
                        </div>
                    </div>

                    <div class="col-md-6 widget">
                        <h3 class="widget-title"></h3>
                        <div class="widget-body">
                            <p></p>
                            <p></p>
                        </div>
                    </div>

                </div> <!-- /row of widgets -->
            </div>
        </div>

        <div class="footer2">
            <div class="container">
                <div class="row">

                    <div class="col-md-6 widget">
                        <div class="widget-body">
                            <p class="simplenav">
                                <a asp-controller="Home" asp-action="Index">Ana Menü</a> |
                                <a asp-controller="Article" asp-action="Index">Yazılar</a> |
                                <a asp-controller="Contact" asp-action="Index">İletişim</a> |
                                <b><a asp-area="Identity" asp-page="/Account/Register">Kayıt Ol</a></b>
                            </p>
                        </div>
                    </div>

                    <div class="col-md-6 widget">
                        <div class="widget-body">
                            <p class="text-right">
                                Copyright &copy; 2021, Yusuf Sönmez. Designed by SomeOne</a>
                            </p>
                        </div>
                    </div>

                </div> <!-- /row of widgets -->
            </div>
        </div>

    </footer>





    <!-- JavaScript libs are placed at the end of the document so the pages load faster -->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="http://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
    <script src="~/js/headroom.min.js"></script>
    <script src="~/js/jQuery.headroom.min.js"></script>
    <script src="~/js/template.js"></script>
    <script src="~/js/respond.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>